#version 450
layout(input_attachment_index = 0, set = 0, binding = 0) uniform subpassInput ia0;
layout(input_attachment_index = 1, set = 0, binding = 1) uniform subpassInput ia1;
layout(input_attachment_index = 2, set = 0, binding = 2) uniform subpassInput ia2;
layout(input_attachment_index = 3, set = 0, binding = 3) uniform subpassInput ia3;
layout(input_attachment_index = 4, set = 0, binding = 4) uniform subpassInput ia4;
layout(input_attachment_index = 5, set = 0, binding = 5) uniform subpassInput ia5;
layout(input_attachment_index = 6, set = 0, binding = 6) uniform subpassInput ia6;
layout(input_attachment_index = 7, set = 0, binding = 7) uniform subpassInput ia7;
layout(input_attachment_index = 8, set = 0, binding = 8) uniform subpassInput ia8;
layout(input_attachment_index = 9, set = 0, binding = 9) uniform subpassInput ia9;
layout(input_attachment_index = 10, set = 0, binding = 10) uniform subpassInput ia10;
layout(input_attachment_index = 11, set = 0, binding = 11) uniform subpassInput ia11;
layout(input_attachment_index = 12, set = 0, binding = 12) uniform subpassInput ia12;
layout(input_attachment_index = 13, set = 0, binding = 13) uniform subpassInput ia13;
layout(input_attachment_index = 14, set = 0, binding = 14) uniform subpassInput ia14;
layout(input_attachment_index = 15, set = 0, binding = 15) uniform subpassInput ia15;
layout(input_attachment_index = 16, set = 0, binding = 16) uniform subpassInput ia16;
layout(input_attachment_index = 17, set = 0, binding = 17) uniform subpassInput ia17;
layout(input_attachment_index = 18, set = 0, binding = 18) uniform subpassInput ia18;
layout(input_attachment_index = 19, set = 0, binding = 19) uniform subpassInput ia19;
layout(location = 0) out vec4 o;
void main() { vec4 s = vec4(0.0);
    s += subpassLoad(ia0);
    s += subpassLoad(ia1);
    s += subpassLoad(ia2);
    s += subpassLoad(ia3);
    s += subpassLoad(ia4);
    s += subpassLoad(ia5);
    s += subpassLoad(ia6);
    s += subpassLoad(ia7);
    s += subpassLoad(ia8);
    s += subpassLoad(ia9);
    s += subpassLoad(ia10);
    s += subpassLoad(ia11);
    s += subpassLoad(ia12);
    s += subpassLoad(ia13);
    s += subpassLoad(ia14);
    s += subpassLoad(ia15);
    s += subpassLoad(ia16);
    s += subpassLoad(ia17);
    s += subpassLoad(ia18);
    s += subpassLoad(ia19);
    o = vec4(s.r, 0.0, 0.0, 1.0); }
